[package]
name = "signal-ping"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = "5.5.0"
zvariant = "5.4.0"
futures-util = "0.3.31"

[dependencies.async-std]
version = "1.13.1"
features = ["attributes"]
