[package]
name = "kademlia"
version = "0.1.0"
authors = ["hwipl"]
edition = "2021"

[dependencies]
libp2p = { version = "0.52.1", features = ["kad", "tcp", "dns", "async-std", "websocket", "noise", "yamux"] }
futures = "0.3.28"
