[package]
name = "hello-server"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = "3.12.0"
zvariant = "3.12.0"
futures-util = "0.3.28"

[dependencies.async-std]
version = "1.12.0"
features = ["attributes"]
