[package]
name = "hello-client"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = "2.0.0-beta.7"
zvariant = "2.9.0"
futures-util = "0.3.17"

[dependencies.async-std]
version = "1.10.0"
features = ["attributes"]
