[package]
name = "request"
version = "0.1.0"
authors = ["hwipl"]
edition = "2021"

[dependencies]
libp2p = { version = "0.51.0", features = ["tcp", "dns", "async-std", "websocket", "noise", "mplex", "yamux", "request-response"] }
futures = "0.3.26"
async-trait = "0.1.66"
