[package]
name = "request"
version = "0.1.0"
authors = ["hwipl"]
edition = "2024"

[dependencies]
libp2p = { version = "0.55.0", features = ["tokio", "tcp", "tls", "noise", "yamux", "dns", "request-response"] }
futures = "0.3.31"
async-trait = "0.1.88"
tokio = "1.44.2"
