[package]
name = "request"
version = "0.1.0"
authors = ["hwipl"]
edition = "2021"

[dependencies]
libp2p = { version = "0.51.2", features = ["tcp", "dns", "async-std", "websocket", "noise", "mplex", "yamux", "request-response"] }
futures = "0.3.28"
async-trait = "0.1.68"
