[package]
name = "request"
version = "0.1.0"
authors = ["hwipl"]
edition = "2021"

[dependencies]
libp2p = { version = "0.54.1", features = ["async-std", "tcp", "tls", "noise", "yamux", "dns", "request-response"] }
futures = "0.3.30"
async-trait = "0.1.82"
