[package]
name = "request"
version = "0.1.0"
authors = ["hwipl"]
edition = "2024"

[dependencies]
libp2p = { version = "0.56.0", features = ["tokio", "tcp", "tls", "noise", "yamux", "dns", "request-response"] }
futures = "0.3.31"
async-trait = "0.1.89"
tokio = "1.47.1"
