[package]
name = "gossip"
version = "0.1.0"
authors = ["hwipl"]
edition = "2021"

[dependencies]
libp2p = { version = "0.55.0", features = ["tokio", "tcp", "tls", "noise", "yamux", "dns", "gossipsub"] }
futures = "0.3.31"
tokio = "1.44.1"
